[package]
name = "mockito"
version = "0.1.1"
authors = ["Florin Lipan <florinlipan@gmail.com>"]

[lib]
doctest = false

[features]
default = []
use_hyper = ["hyper", "url"]
mock_hyper = ["use_hyper"]
mock_tcp_stream = []

[dependencies]
hyper = { version = "0.7.1", optional = true }
url = { version = "0.5", optional = true }
