[package]
name = "mockito"
version = "0.1.4"
authors = ["Florin Lipan <florinlipan@gmail.com>"]
license = "MIT"
repository = "https://github.com/lipanski/mockito"
description = "Easy web-mocking for Rust. This is a work in progress!"

[dependencies]
hyper = "0.9.6"
rustc-serialize = "0.3.19"

[lib]
doctest = false
