[package]
name = "mockito"
version = "0.2.0"
authors = ["Florin Lipan <florinlipan@gmail.com>"]
license = "MIT"
homepage = "https://github.com/lipanski/mockito"
repository = "https://github.com/lipanski/mockito"
documentation = "http://lipanski.github.io/mockito"
description = "HTTP mocking for Rust"

[dependencies]
hyper = "0.9.6"
rustc-serialize = "0.3.19"
rand = "0.3.14"
